fix(readme) update prerequisites
CHUPITO-Org/IaC-Chupito-AWS pull request #16
Opened 2024-01-23 16:34 UTC by Naldo-reupo-LIM

## AWS - Web App

## Issue ticket number and link

## Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed
- [ ] My changes generate no new warnings or errors

## Pull request type

Please check the type of change your PR introduces:

- [ ] :sparkles: Feature Implementation
- [ ] :bug: Bugfix
- [ ] :art: Code Formatting (formatting, renaming)
- [ ] :recycle: Refactoring
- [ ] :pencil: Documentation content changes
- [ ] :white_check_mark: Unit testing
- [ ] :hammer: Automated testing
- [ ] :zap:  Dependency update
- [ ] :wrench: Add or update configuration files

## What is the current module?

-

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

2024-01-23 20:47 UTC, jose-sal-y-rosas approved these changes
👍🏼

2024-01-24 14:14 UTC, pramirezma requested changes
Can you move your explanation of local development to another .md?

2024-01-24 17:32 UTC, Naldo-reupo-LIM commented
> Can you move your explanation of local development to another .md?



> Can you move your explanation of local development to another .md?
All references to prvate deployement removed

2024-01-24 20:13 UTC, pramirezma approved these changes

2024-01-25 15:50 UTC, merged