Laura/feat/create vpc
CHUPITO-Org/IaC-Chupito-AWS pull request #4
Opened 2023-11-13 22:32 UTC by Lmam22

2023-11-14 15:02 UTC, pramirezma approved these changes

2023-11-15 13:32 UTC, pramirezma approved these changes

2023-11-15 16:55 UTC, jose-sal-y-rosas requested changes
Please review feedback

2023-11-15 16:55 UTC, jose-sal-y-rosas commented on modules/vpc_manual/natgw.tf
> +  #count  = length(var.public_subnet_cidrs)
Please remove this line.

2023-11-15 16:55 UTC, jose-sal-y-rosas commented on modules/vpc_manual/natgw.tf
> +  #count      = length(var.private_subnet_cidrs)
Please remove this line

2023-11-15 16:55 UTC, jose-sal-y-rosas commented on modules/vpc_manual/subnets.tf
> +    Name = "public-chupito-${count.index + 1}"
Name = "public-subnet-${count.index + 1}"
Project = "chupito"

2023-11-15 16:55 UTC, jose-sal-y-rosas commented on modules/vpc_manual/igw.tf
> +    Name = "chupito"
Project = "chupito"

2023-11-15 17:16 UTC, jose-sal-y-rosas approved these changes

2023-11-15 17:23 UTC, merged