feat(ecr): create first version of registry and docker image
CHUPITO-Org/IaC-Chupito-AWS pull request #5
Opened 2023-11-15 18:17 UTC by Lmam22

Create a first version of registry and docker image

2023-11-16 05:24 UTC, jose-sal-y-rosas requested changes
Please review feedback

2023-11-16 05:24 UTC, jose-sal-y-rosas commented on locals.tf
> +# locals {
Please remove this file if all content is commented

2023-11-16 05:24 UTC, jose-sal-y-rosas commented on main.tf
> +module "ecr-repo" {
Please use a generic name such as 'container_registry'

2023-11-16 05:24 UTC, jose-sal-y-rosas commented on providers.tf
> +# provider "docker" {
Please remove this section if it not used

2023-11-16 12:54 UTC, pramirezma reviewed
At the end, you are using Terraform Cloud for the variables?

2023-11-16 13:06 UTC, Lmam22 commented
> At the end, you are using Terraform Cloud for the variables?

Just for AWS_ACCESS_KEY_ID, AWS_SECRET_KEY_ID and SESSION_TOKEN

2023-11-16 13:13 UTC, Lmam22 reviewed
done

2023-11-16 13:13 UTC, Lmam22 commented on locals.tf
> +# locals {
Ok

2023-11-16 13:26 UTC, Lmam22 commented
Helllo World with ECS and Fargate: http://example-lb-110786881.us-east-1.elb.amazonaws.com/
![image](https://github.com/CHUPITO-Org/IaC-Chupito-AWS/assets/87614516/108b3a83-3687-4a07-9e32-c08e55219a64)

2023-11-16 13:33 UTC, pramirezma commented
Is not a bad idea just do it in only one part, just to not "overcomplicate" the setup

2023-11-16 13:33 UTC, pramirezma approved these changes

2023-11-20 15:00 UTC, Lmam22 commented
http://example-lb-208770439.us-east-1.elb.amazonaws.com/

![image](https://github.com/CHUPITO-Org/IaC-Chupito-AWS/assets/87614516/762c7bb8-40ca-4f2a-a92f-73ba4cc7109d)

2023-11-20 16:05 UTC, pramirezma commented
Remove the comments if there is no need to have them

2023-11-20 16:28 UTC, jose-sal-y-rosas requested changes
Please review feedback

2023-11-20 16:28 UTC, jose-sal-y-rosas commented on modules/ecr/variables.tf
> +variable "aws_region" {}
Are these variables don't required a description?

2023-11-20 16:28 UTC, jose-sal-y-rosas commented on modules/ecs/alb.tf
> +  # count                   = length(var.public_subnets_ids) #2
Please remove commented lines

2023-11-20 16:28 UTC, jose-sal-y-rosas commented on modules/ecs/cluster.tf
> +    #container_port   = 3000
Please remove commented lines

2023-11-20 16:28 UTC, jose-sal-y-rosas commented on modules/ecs/ecs_task.tf
> +  #"image": "${aws_ecr_repository.ecr.repository_url}",
Please remove commented line

2023-11-20 16:28 UTC, jose-sal-y-rosas commented on modules/ecs/ecs_task.tf
> +resource "aws_ecs_task_definition" "hello_world" {
hello world as name of the resource?

2023-11-20 16:28 UTC, jose-sal-y-rosas commented on modules/ecs/ecs_task.tf
> +    #from_port       = 3000
Please remove all commented lines

2023-11-20 17:20 UTC, Lmam22 commented
http://alb-chupito-1636170153.us-east-1.elb.amazonaws.com/

![image](https://github.com/CHUPITO-Org/IaC-Chupito-AWS/assets/87614516/f2d42a31-5df5-4925-8765-aac9977defcd)

2023-11-20 18:15 UTC, pramirezma approved these changes

2023-11-20 18:19 UTC, pamelaluquemck approved these changes

2023-11-20 18:28 UTC, jose-sal-y-rosas requested changes
Please review feedback

2023-11-20 18:28 UTC, jose-sal-y-rosas commented on modules/ecr/variables.tf
> +variable "aws_region" {}
Please add the description for these variables.

2023-11-20 20:20 UTC, jose-sal-y-rosas approved these changes
👍🏼

2023-11-20 20:32 UTC, merged